name: Gradle wrapper validation
on:
  pull_request:
    paths:
      - '**/gradle/wrapper/**'
  push:
    branches:
      - main
    paths:
      - '**/gradle/wrapper/**'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3.5.0
